-- Doctrine Migration File Generated on 2020-03-03 13:26:59

-- Version 20200303131955
ALTER TABLE inscription_typeinscription DROP FOREIGN KEY FK_E6BA6DB95DAC5993;
ALTER TABLE question DROP FOREIGN KEY FK_B6F7494ECF18BB82;
ALTER TABLE inscription_typeinscription DROP FOREIGN KEY FK_E6BA6DB98211AE88;
ALTER TABLE inscription DROP FOREIGN KEY FK_5E90F6D6B981C689;
DROP TABLE inscription;
DROP TABLE inscription_typeinscription;
DROP TABLE question;
DROP TABLE reponse;
DROP TABLE typeinscription;
DROP TABLE utilisateur;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200303131955', CURRENT_TIMESTAMP);

-- Version 20200303132251
ALTER TABLE inscription_typeinscription DROP FOREIGN KEY FK_E6BA6DB95DAC5993;
ALTER TABLE question DROP FOREIGN KEY FK_B6F7494ECF18BB82;
ALTER TABLE inscription_typeinscription DROP FOREIGN KEY FK_E6BA6DB98211AE88;
ALTER TABLE inscription DROP FOREIGN KEY FK_5E90F6D6B981C689;
DROP TABLE inscription;
DROP TABLE inscription_typeinscription;
DROP TABLE question;
DROP TABLE reponse;
DROP TABLE typeinscription;
DROP TABLE utilisateur;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200303132251', CURRENT_TIMESTAMP);

-- Version 20200303132506
CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE reponse (id INT AUTO_INCREMENT NOT NULL, libelle_reponse VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE utilisateur (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200303132506', CURRENT_TIMESTAMP);

-- Version 20200303132604
CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE reponse (id INT AUTO_INCREMENT NOT NULL, libelle_reponse VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE utilisateur (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, mdp VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200303132604', CURRENT_TIMESTAMP);
